### ISSUE TITLE
Administração - Configurações

### ISSUE THREAD

**Issue by luisdiasbh** [MPMG-DCC-UFMG/P01#1]
Não consigo acessar administração/configurações com um usuário do LDAP.

![lemonade01](https://user-images.githubusercontent.com/67106220/89339340-60fd8800-d674-11ea-93d5-0166a6dd3387.png)

**Comment by waltersf** [comment]
Corrigido. Para acesso ao menu de Configurações é necessária a permissão de ADMINISTRATOR.
